export const FETCH_ALL = 'FETCH_ALL';
export const FETCH_FORM = 'FETCH_FORM';
export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';
export const ERROR = 'ERROR';
export const CREATE = 'CREATE';
export const UPDATE = 'UPDATE';
export const UPDATE_SUCCESSFUL = 'UPDATE_SUCCESSFUL';
export const DELETE = 'DELETE';
export const DELETE_SUCCESSFUL = 'DELETE_SUCCESSFUL';
export const ADD_ANSWER_SUCCESSFUL = 'ADD_ANSWER_SUCCESSFUL';
export const GET_ANSWERS = 'GET_ANSWERS';

export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const REFRESH_TOKEN_FAIL = 'REFRESH_TOKEN_FAIL';
export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';
export const SET_MINIMIZE_REQUEST = 'SET_MINIMIZE_REQUEST';
export const SET_COLOR_THEME_REQUEST = 'SET_COLOR_THEME_REQUEST';
export const SET_OPEN_MOBILE_REQUEST = 'SET_OPEN_MOBILE_REQUEST';


// =====================      Auth action types START    =========================

// load logged in user
export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST'
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS'
export const LOAD_USER_UPDATE = 'LOAD_USER_UPDATE'
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL'

//load company users 
export const LOAD_TOKEN_REQUEST = 'LOAD_TOKEN_REQUEST'
export const LOAD_TOKEN_SUCCESS = 'LOAD_TOKEN_SUCCESS'
export const LOAD_TOKEN_FAIL = 'LOAD_TOKEN_FAIL'
export const LOAD_TOKEN_RESET = 'LOAD_TOKEN_RESET'

//deactivate user

export const DEACTIVATE_USER_REQUEST = 'DEACTIVATE_USER_REQUEST'
export const DEACTIVATE_USER_SUCCESS = 'DEACTIVATE_USER_SUCCESS'
export const DEACTIVATE_USER_FAIL = 'DEACTIVATE_USER_FAIL'
export const DEACTIVATE_USER_RESET = 'DEACTIVATE_USER_RESET'

//get verified user
export const VERIFIED_USER_REQUEST = 'VERIFIED_USER_REQUEST'
export const VERIFIED_USER_SUCCESS = 'VERIFIED_USER_SUCCESS'
export const VERIFIED_USER_FAIL = 'VERIFIED_USER_FAIL'
export const VERIFIED_USER_RESET = 'VERIFIED_USER_RESET'

//get unverified user
export const UNVERIFIED_USER_REQUEST = 'UNVERIFIED_USER_REQUEST'
export const UNVERIFIED_USER_SUCCESS = 'UNVERIFIED_USER_SUCCESS'
export const UNVERIFIED_USER_FAIL = 'UNVERIFIED_USER_FAIL'
export const UNVERIFIED_USER_RESET = 'UNVERIFIED_USER_RESET'

// login 
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const AUTH_RESET = 'AUTH_RESET'

// logout 
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'
export const LOGOUT_RESET = 'LOGOUT_RESET'

// register employee
export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const REGISTER_RESET = 'REGISTER_RESET'

// register admin
export const REGISTER_ADMIN_REQUEST = 'REGISTER_ADMIN_REQUEST'
export const REGISTER_ADMIN_SUCCESS = 'REGISTER_ADMIN_SUCCESS'
export const REGISTER_ADMIN_FAIL = 'REGISTER_ADMIN_FAIL'
export const REGISTER_ADMIN_RESET = 'REGISTER_ADMIN_RESET'

// email confirmation
export const VERIFY_EMAIL_REQUEST = 'VERIFY_EMAIL_REQUEST'
export const VERIFY_EMAIL_SUCCESS = 'VERIFY_EMAIL_SUCCESS'
export const VERIFY_EMAIL_FAIL = 'VERIFY_EMAIL_FAIL'
export const VERIFY_EMAIL_RESET = 'VERIFY_EMAIL_RESET'

// load user 
export const GET_USER_REQUEST = 'GET_USER_REQUEST'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAIL = 'GET_USER_FAIL'

// send verification email 
export const RESEND_VERIFY_EMAIL_REQUEST = 'RESEND_VERIFY_EMAIL_REQUEST'
export const RESEND_VERIFY_EMAIL_SUCCESS = 'RESEND_VERIFY_EMAIL_SUCCESS'
export const RESEND_VERIFY_EMAIL_FAIL = 'RESEND_VERIFY_EMAIL_FAIL'
export const RESEND_VERIFY_EMAIL_RESET = 'RESEND_VERIFY_EMAIL_RESET'

// get user by email
export const GET_USER_BY_EMAIL_REQUEST = 'GET_USER_BY_EMAIL_REQUEST'
export const GET_USER_BY_EMAIL_SUCCESS = 'GET_USER_BY_EMAIL_SUCCESS'
export const GET_USER_BY_EMAIL_FAIL = 'GET_USER_BY_EMAIL_FAIL'
export const GET_USER_BY_EMAIL_RESET = 'GET_USER_BY_EMAIL_RESET'

// get user by email
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL'
export const RESET_PASSWORD_RESET = 'RESET_PASSWORD_RESET'

// show avatar preview
export const SHOW_AVATAR_PREVIEW_SUCCESS = 'SHOW_AVATAR_PREVIEW_SUCCESS'

// update USER profile
export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL'
export const UPDATE_PROFILE_RESET = 'UPDATE_PROFILE_RESET'

// update USER profile
export const LOAD_PROFILE_REQUEST = 'LOAD_PROFILE_REQUEST'
export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS'
export const LOAD_PROFILE_FAIL = 'LOAD_PROFILE_FAIL'
export const LOAD_PROFILE_RESET = 'LOAD_PROFILE_RESET'

// update password
export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST'
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS'
export const UPDATE_PASSWORD_FAIL = 'UPDATE_PASSWORD_FAIL'
export const UPDATE_PASSWORD_RESET = 'UPDATE_PASSWORD_RESET'
// =====================      Auth action types END    =========================

// load DASHBOARD
export const GET_ADMIN_DASHBOARD_REQUEST = 'GET_ADMIN_DASHBOARD_REQUEST'
export const GET_ADMIN_DASHBOARD_SUCCESS = 'GET_ADMIN_DASHBOARD_SUCCESS'
export const GET_ADMIN_DASHBOARD_FAIL = 'GET_ADMIN_DASHBOARD_FAIL'
export const CLEAR_GET_ADMIN_DASHBOARD = 'CLEAR_GET_ADMIN_DASHBOARD'

// load ADMIN DASHBOARD PROJECT
export const GET_ADMIN_DASHBOARD_PROJECT_REQUEST = 'GET_ADMIN_DASHBOARD_PROJECT_REQUEST'
export const GET_ADMIN_DASHBOARD_PROJECT_SUCCESS = 'GET_ADMIN_DASHBOARD_PROJECT_SUCCESS'
export const GET_ADMIN_DASHBOARD_PROJECT_FAIL = 'GET_ADMIN_DASHBOARD_PROJECT_FAIL'
export const CLEAR_GET_ADMIN_DASHBOARD_PROJECT = 'CLEAR_GET_ADMIN_DASHBOARD_PROJECT'



// =====================   driver action types Start   =========================
// load driver
export const LOAD_DRIVER_REQUEST = 'LOAD_DRIVER_REQUEST'
export const LOAD_DRIVER_SUCCESS = 'LOAD_DRIVER_SUCCESS'
export const LOAD_DRIVER_FAIL = 'LOAD_DRIVER_FAIL'
export const LOAD_DRIVER_RESET = 'LOAD_DRIVER_RESET'
// load DRIVER
export const GET_DRIVER_REQUEST = 'GET_DRIVER_REQUEST'
export const GET_DRIVER_SUCCESS = 'GET_DRIVER_SUCCESS'
export const GET_DRIVER_FAIL = 'GET_DRIVER_FAIL'
export const CLEAR_GET_DRIVERS = 'CLEAR_GET_DRIVERS'
// Create User
export const CREATE_DRIVER_REQUEST = 'CREATE_DRIVER_REQUEST'
export const CREATE_DRIVER_SUCCESS = 'CREATE_DRIVER_SUCCESS'
export const CREATE_DRIVER_FAIL = 'CREATE_DRIVER_FAIL'
export const CLEAR_DRIVER = 'CLEAR_DRIVER'
// assign driver
export const ASSIGN_DRIVER_REQUEST = 'ASSIGN_DRIVER_REQUEST'
export const ASSIGN_DRIVER_SUCCESS = 'ASSIGN_DRIVER_SUCCESS'
export const ASSIGN_DRIVER_FAIL = 'ASSIGN_DRIVER_FAIL'
export const ASSIGN_DRIVER_RESET = 'ASSIGN_DRIVER_RESET'
// remove bulk event
export const REMOVE_BULK_EVENT_REQUEST = 'REMOVE_BULK_EVENT_REQUEST'
export const REMOVE_BULK_EVENT_SUCCESS = 'REMOVE_BULK_EVENT_SUCCESS'
export const REMOVE_BULK_EVENT_FAIL = 'REMOVE_BULK_EVENT_FAIL'
export const REMOVE_BULK_EVENT_RESET = 'REMOVE_BULK_EVENT_RESET'
// delete DRIVER
export const DELETE_DRIVER_REQUEST = 'DELETE_DRIVER_REQUEST'
export const DELETE_DRIVER_SUCCESS = 'DELETE_DRIVER_SUCCESS'
export const DELETE_DRIVER_FAIL = 'DELETE_DRIVER_FAIL'
export const DELETE_DRIVER_RESET = 'DELETE_DRIVER_RESET'
// update DRIVER
export const UPDATE_DRIVER_REQUEST = 'UPDATE_DRIVER_REQUEST'
export const UPDATE_DRIVER_SUCCESS = 'UPDATE_DRIVER_SUCCESS'
export const UPDATE_DRIVER_FAIL = 'UPDATE_DRIVER_FAIL'
export const UPDATE_DRIVER_RESET = 'UPDATE_DRIVER_RESET'
// deactivate DRIVER
export const DEACTIVATE_DRIVER_REQUEST = 'DEACTIVATE_DRIVER_REQUEST'
export const DEACTIVATE_DRIVER_SUCCESS = 'DEACTIVATE_DRIVER_SUCCESS'
export const DEACTIVATE_DRIVER_FAIL = 'DEACTIVATE_DRIVER_FAIL'
export const DEACTIVATE_DRIVER_RESET = 'DEACTIVATE_DRIVER_RESET'
// HET HOS RULES
// load USER
export const GET_HOS_RULES_REQUEST = 'GET_HOS_RULES_REQUEST'
export const GET_HOS_RULES_SUCCESS = 'GET_USER_SUCCESS'
export const GET_HOS_RULES_FAIL = 'GET_HOS_RULES_FAIL'
export const CLEAR_GET_HOS_RULES = 'CLEAR_GET_HOS_RULES'
// =====================  Ends Client action types Start   =========================
// =====================   VEHICLE action types Start   =========================
// load VEHICLE
export const GET_VEHICLE_REQUEST = 'GET_VEHICLE_REQUEST'
export const GET_VEHICLE_SUCCESS = 'GET_VEHICLE_SUCCESS'
export const GET_VEHICLE_FAIL = 'GET_VEHICLE_FAIL'
export const CLEAR_GET_VEHICLES = 'CLEAR_GET_VEHICLES'

//get vehicle
export const GET_VEHICLE_LOCATION_REQUEST = 'GET_VEHICLE_LOCATION_REQUEST'
export const GET_VEHICLE_LOCATION_SUCCESS = 'GET_VEHICLE_LOCATION_SUCCESS'
export const GET_VEHICLE_LOCATION_FAIL = 'GET_VEHICLE_LOCATION_FAIL'
export const CLEAR_GET_VEHICLE_LOCATION = 'CLEAR_GET_VEHICLE_LOCATION'

// Create User
export const CREATE_VEHICLE_REQUEST = 'CREATE_VEHICLE_REQUEST'
export const CREATE_VEHICLE_SUCCESS = 'CREATE_VEHICLE_SUCCESS'
export const CREATE_VEHICLE_FAIL = 'CREATE_VEHICLE_FAIL'
export const CLEAR_VEHICLE = 'CLEAR_VEHICLE'
// delete VEHICLE
export const DELETE_VEHICLE_REQUEST = 'DELETE_VEHICLE_REQUEST'
export const DELETE_VEHICLE_SUCCESS = 'DELETE_VEHICLE_SUCCESS'
export const DELETE_VEHICLE_FAIL = 'DELETE_VEHICLE_FAIL'
export const DELETE_VEHICLE_RESET = 'DELETE_VEHICLE_RESET'
// load driver
export const LOAD_VEHICLE_REQUEST = 'LOAD_VEHICLE_REQUEST'
export const LOAD_VEHICLE_SUCCESS = 'LOAD_VEHICLE_SUCCESS'
export const LOAD_VEHICLE_FAIL = 'LOAD_VEHICLE_FAIL'
export const LOAD_VEHICLE_RESET = 'LOAD_VEHICLE_RESET'
// update VEHICLE
export const UPDATE_VEHICLE_REQUEST = 'UPDATE_VEHICLE_REQUEST'
export const UPDATE_VEHICLE_SUCCESS = 'UPDATE_VEHICLE_SUCCESS'
export const UPDATE_VEHICLE_FAIL = 'UPDATE_VEHICLE_FAIL'
export const UPDATE_VEHICLE_RESET = 'UPDATE_VEHICLE_RESET'
// Master VEHICLE
export const GET_VEHICLE_MASTER_REQUEST = 'VEHICLE_MASTER_REQUEST'
export const GET_VEHICLE_MASTER_SUCCESS = 'VEHICLE_MASTER_SUCCESS'
export const GET_VEHICLE_MASTER_FAIL = 'VEHICLE_MASTER_FAIL'
export const CLEAR_GET_VEHICLE_MASTER = 'VEHICLE_MASTER_CLEAR'
// UNASSIGN VEHICLE
export const GET_UNASSIGN_VEHICLE_REQUEST = 'GET_UNASSIGN_VEHICLE_REQUEST'
export const GET_UNASSIGN_VEHICLE_SUCCESS = 'GET_UNASSIGN_VEHICLE_SUCCESS'
export const GET_UNASSIGN_VEHICLE_FAIL = 'GET_UNASSIGN_VEHICLE_FAIL'
export const GET_UNASSIGN_VEHICLE_RESET = 'GET_UNASSIGN_VEHICLE_RESET'
// Deactivate VEHICLE
export const DEACTIVATE_VEHICLE_REQUEST = 'DEACTIVATE_VEHICLE_REQUEST'
export const DEACTIVATE_VEHICLE_SUCCESS = 'DEACTIVATE_VEHICLE_SUCCESS'
export const DEACTIVATE_VEHICLE_FAIL    = 'DEACTIVATE_VEHICLE_FAIL'
export const DEACTIVATE_VEHICLE_RESET   = 'DEACTIVATE_VEHICLE_RESET'
//Active Vehicle List
export const GET_ACTIVE_VEHICLE_REQUEST = 'GET_ACTIVE_VEHICLE_REQUEST'
export const GET_ACTIVE_VEHICLE_SUCCESS = 'GET_ACTIVE_VEHICLE_SUCCESS'
export const GET_ACTIVE_VEHICLE_FAIL = 'GET_ACTIVE_VEHICLE_FAIL'
export const CLEAR_GET_ACTIVE_VEHICLES = 'CLEAR_GET_ACTIVE_VEHICLES'
// =====================  Ends VEHICLE action types Start   =========================
// =====================   ELD_DEVICES action types Start   =========================
// load ELD_DEVICES
export const GET_ELD_DEVICES_REQUEST = 'GET_ELD_DEVICES_REQUEST'
export const GET_ELD_DEVICES_SUCCESS = 'GET_ELD_DEVICES_SUCCESS'
export const GET_ELD_DEVICES_FAIL = 'GET_ELD_DEVICES_FAIL'
export const CLEAR_GET_ELD_DEVICESS = 'CLEAR_GET_ELD_DEVICESS'
// Create User
export const CREATE_ELD_DEVICES_REQUEST = 'CREATE_ELD_DEVICES_REQUEST'
export const CREATE_ELD_DEVICES_SUCCESS = 'CREATE_ELD_DEVICES_SUCCESS'
export const CREATE_ELD_DEVICES_FAIL = 'CREATE_ELD_DEVICES_FAIL'
export const CLEAR_ELD_DEVICES = 'CLEAR_ELD_DEVICES'
//deactivate ELD DEVICES
export const DEACTIVATE_ELD_DEVICE_REQUEST = 'DEACTIVATE_ELD_DEVICE_REQUEST'
export const DEACTIVATE_ELD_DEVICE_SUCCESS = 'DEACTIVATE_ELD_DEVICE_SUCCESS'
export const DEACTIVATE_ELD_DEVICE_FAIL =   'DEACTIVATE_ELD_DEVICE_FAIL'
export const DEACTIVATE_ELD_DEVICE_RESET = 'DEACTIVATE_ELD_DEVICE_RESET'
//remove ELD DEVICES
export const REMOVE_ELD_DEVICE_REQUEST = 'REMOVE_ELD_DEVICE_REQUEST'
export const REMOVE_ELD_DEVICE_SUCCESS = 'REMOVE_ELD_DEVICE_SUCCESS'
export const REMOVE_ELD_DEVICE_FAIL = 'REMOVE_ELD_DEVICE_FAIL'
export const REMOVE_ELD_DEVICE_RESET = 'REMOVE_ELD_DEVICE_RESET'
// delete ELD_DEVICES
export const DELETE_ELD_DEVICES_REQUEST = 'DELETE_ELD_DEVICES_REQUEST'
export const DELETE_ELD_DEVICES_SUCCESS = 'DELETE_ELD_DEVICES_SUCCESS'
export const DELETE_ELD_DEVICES_FAIL = 'DELETE_ELD_DEVICES_FAIL'
export const DELETE_ELD_DEVICES_RESET = 'DELETE_ELD_DEVICES_RESET'
// load driver
export const LOAD_ELD_DEVICES_REQUEST = 'LOAD_ELD_DEVICES_REQUEST'
export const LOAD_ELD_DEVICES_SUCCESS = 'LOAD_ELD_DEVICES_SUCCESS'
export const LOAD_ELD_DEVICES_FAIL = 'LOAD_ELD_DEVICES_FAIL'
export const LOAD_ELD_DEVICES_RESET = 'LOAD_ELD_DEVICES_RESET'
// update ELD_DEVICES
export const UPDATE_ELD_DEVICES_REQUEST = 'UPDATE_ELD_DEVICES_REQUEST'
export const UPDATE_ELD_DEVICES_SUCCESS = 'UPDATE_ELD_DEVICES_SUCCESS'
export const UPDATE_ELD_DEVICES_FAIL = 'UPDATE_ELD_DEVICES_FAIL'
export const UPDATE_ELD_DEVICES_RESET = 'UPDATE_ELD_DEVICES_RESET'
// Master VEHICLE
export const GET_ELD_MASTER_REQUEST = 'ELD_MASTER_REQUEST'
export const GET_ELD_MASTER_SUCCESS = 'ELD_MASTER_SUCCESS'
export const GET_ELD_MASTER_FAIL = 'ELD_MASTER_FAIL'
export const CLEAR_GET_ELD_MASTER = 'ELD_MASTER_CLEAR'
// =====================  Ends ELD_DEVICES action types Start   =========================
// =====================   USER action types Start   =========================
// load USER
export const LOAD_USERS_REQUEST = 'LOAD_USERS_REQUEST'
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS'
export const LOAD_USERS_FAIL = 'LOAD_USERS_FAIL'
export const LOAD_USERS_RESET = 'LOAD_USERS_RESET'
// load USER
export const GET_USERS_REQUEST = 'GET_USERS_REQUEST'
export const GET_USERS_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USERS_FAIL = 'GET_USERS_FAIL'
export const CLEAR_GET_USERS = 'CLEAR_GET_USERS'
// Create User
export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL'
export const CLEAR_USER = 'CLEAR_USER'
// delete USER
export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL'
export const DELETE_USER_RESET = 'DELETE_USER_RESET'
// update USER
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL'
export const UPDATE_USER_RESET = 'UPDATE_USER_RESET'
// =====================  Ends USER action types Start   =========================
// =====================   Company action types Start   =========================
// load Company
export const LOAD_COMPANY_REQUEST = 'LOAD_COMPANY_REQUEST'
export const LOAD_COMPANY_SUCCESS = 'LOAD_COMPANY_SUCCESS'
export const LOAD_COMPANY_FAIL = 'LOAD_COMPANY_FAIL'
export const LOAD_COMPANY_RESET = 'LOAD_COMPANY_RESET'
// load Company Users
export const LOAD_COMPANY_USERS_REQUEST = 'LOAD_COMPANY_USERS_REQUEST'
export const LOAD_COMPANY_USERS_SUCCESS = 'LOAD_COMPANY_USERS_SUCCESS'
export const LOAD_COMPANY_USERS_FAIL = 'LOAD_COMPANY_USERS_FAIL'
export const LOAD_COMPANY_USERS_RESET = 'LOAD_COMPANY_USERS_RESET'
// update Company
export const UPDATE_COMPANY_REQUEST = 'UPDATE_COMPANY_REQUEST'
export const UPDATE_COMPANY_SUCCESS = 'UPDATE_COMPANY_SUCCESS'
export const UPDATE_COMPANY_FAIL = 'UPDATE_COMPANY_FAIL'
export const UPDATE_COMPANY_RESET = 'UPDATE_COMPANY_RESET'
//GET ALL COMPANY
// load Company
export const LOAD_COMPANIES_REQUEST = 'LOAD_COMPANIES_REQUEST'
export const LOAD_COMPANIES_SUCCESS = 'LOAD_COMPANIES_SUCCESS'
export const LOAD_COMPANIES_FAIL = 'LOAD_COMPANIES_FAIL'
export const LOAD_COMPANIES_RESET = 'LOAD_COMPANIES_RESET'
//load companies data for fmcsa records
export const LOAD_COMPANIES_DATA_REQUEST = 'LOAD_COMPANIES_DATA_REQUEST'
export const LOAD_COMPANIES_DATA_SUCCESS = 'LOAD_COMPANIES_DATA_SUCCESS'
export const LOAD_COMPANIES_DATA_FAIL = 'LOAD_COMPANIES_DATA_FAIL'
export const LOAD_COMPANIES_DATA_RESET = 'LOAD_COMPANIES_DATA_RESET'
//create company
export const CREATE_COMPANY_REQUEST = 'CREATE_COMPANY_REQUEST'
export const CREATE_COMPANY_SUCCESS = 'CREATE_COMPANY_SUCCESS'
export const CREATE_COMPANY_FAIL = 'CREATE_COMPANY_FAIL'
export const CREATE_COMPANY_RESET = 'CREATE_COMPANY_RESET'

// =====================  Ends Company action types Start   =========================
// ===================== Logs action types Start ====================================

export const SET_LOG_FILTER_DATE = 'SET_LOG_FILTER_DATE'

export const LOAD_LOGS_REQUEST = 'LOAD_LOGS_REQUEST'
export const LOAD_LOGS_SUCCESS = 'LOAD_LOGS_SUCCESS'
export const LOAD_LOGS_FAIL = 'LOAD_LOGS_FAIL'
export const LOAD_LOGS_RESET = 'LOAD_LOGS_RESET'
// load DRIVER
export const GET_LOGS_REQUEST = 'GET_LOGS_REQUEST'
export const GET_LOGS_SUCCESS = 'GET_LOGS_SUCCESS'
export const GET_LOGS_FAIL = 'GET_LOGS_FAIL'
export const CLEAR_GET_LOGS = 'CLEAR_GET_LOGS'
// logs bulk event update
export const BULK_EVENT_UPDATE_REQUEST = 'BULK_EVENT_UPDATE_REQUEST'
export const BULK_EVENT_UPDATE_SUCCESS = 'BULK_EVENT_UPDATE_SUCCESS'
export const BULK_EVENT_UPDATE_FAIL = 'BULK_EVENT_UPDATE_FAIL'
export const BULK_EVENT_UPDATE_RESET = 'BULK_EVENT_UPDATE_RESET'

//GET PDF LOGS 
export const GET_PDF_LOGS_REQUEST = 'GET_PDF_LOGS_REQUEST'
export const GET_PDF_LOGS_SUCCESS = 'GET_PDF_LOGS_SUCCESS'
export const GET_PDF_LOGS_FAIL = 'GET_PDF_LOGS_FAIL'
export const GET_PDF_LOGS_RESET = 'GET_PDF_LOGS_RESET'
//download PDF LOGS
export const DOWNLOAD_PDF_LOGS_REQUEST = 'DOWNLOAD_PDF_LOGS_REQUEST'
export const DOWNLOAD_PDF_LOGS_SUCCESS = 'DOWNLOAD_PDF_LOGS_SUCCESS'
export const DOWNLOAD_PDF_LOGS_FAIL = 'DOWNLOAD_PDF_LOGS_FAIL'
export const DOWNLOAD_PDF_LOGS_RESET = 'DOWNLOAD_PDF_LOGS_RESET'
// download PDF LOGS RANGE
export const DOWNLOAD_PDF_LOGS_RANGE_REQUEST = 'DOWNLOAD_PDF_LOGS_RANGE_REQUEST'
export const DOWNLOAD_PDF_LOGS_RANGE_SUCCESS = 'DOWNLOAD_PDF_LOGS_RANGE_SUCCESS'
export const DOWNLOAD_PDF_LOGS_RANGE_FAIL = 'DOWNLOAD_PDF_LOGS_RANGE_FAIL'
export const DOWNLOAD_PDF_LOGS_RANGE_RESET = 'DOWNLOAD_PDF_LOGS_RANGE_RESET'
//load DRIVER GRAPH 
export const LOAD_CO_DRIVER_GRAPH_LOG_REQUEST = 'LOAD_CO_DRIVER_GRPAH_LOG_REQUEST'
export const LOAD_CO_DRIVER_GRAPH_LOG_SUCCESS = 'LOAD_CO_DRIVER_GRAPH_LOG_SUCCESS'
export const LOAD_CO_DRIVER_GRAPH_LOG_FAIL = 'LOAD_CO_DRIVER_GRAPH_LOG_FAIL'
export const LOAD_CO_DRIVER_GRAPH_LOG_RESET = 'LOAD_CO_DRIVER_GRAPH_LOG_RESET'
//load DRIVER GRAPH 
export const LOAD_GRAPH_LOG_REQUEST = 'LOAD_GRPAH_LOG_REQUEST'
export const LOAD_GRAPH_LOG_SUCCESS = 'LOAD_GRAPH_LOG_SUCCESS'
export const LOAD_GRAPH_LOG_FAIL = 'LOAD_GRAPH_LOG_FAIL'
export const LOAD_GRAPH_LOG_RESET = 'LOAD_GRAPH_LOG_RESET'
//load DRIVER GRAPH 
export const LOAD_EVENT_CODE_REQUEST = 'LOAD_EVENT_CODE_REQUEST'
export const LOAD_EVENT_CODE_SUCCESS = 'LOAD_EVENT_CODE_SUCCESS'
export const LOAD_EVENT_CODE_FAIL = 'LOAD_EVENT_CODE_FAIL'
export const LOAD_EVENT_CODE_RESET = 'LOAD_EVENT_CODE_RESET'
// ===================== Events action types Start ====================================
export const LOAD_EVENTS_REQUEST = 'LOAD_EVENTS_REQUEST'
export const LOAD_EVENTS_SUCCESS = 'LOAD_EVENTS_SUCCESS'
export const LOAD_EVENTS_FAIL = 'LOAD_EVENTS_FAIL'
export const LOAD_EVENTS_RESET = 'LOAD_EVENTS_RESET'
// load Vehicle
export const GET_EVENTS_REQUEST = 'GET_EVENTS_REQUEST'
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS'
export const GET_EVENTS_FAIL = 'GET_EVENTS_FAIL'
export const CLEAR_GET_EVENTS = 'CLEAR_GET_LOGS'
// load Vehicle logs
export const LOAD_VEHICLE_LOG_REQUEST = 'VEHICLE_LOG_REQUEST'
export const LOAD_VEHICLE_LOG_SUCCESS = 'VEHICLE_LOG_SUCCESS'
export const LOAD_VEHICLE_LOG_FAIL = 'VEHICLE_LOG_FAIL'
export const CLEAR_VEHICLE_LOG = 'CLEAR_VEHICLE_LOG'
//load Unidentified Events
export const LOAD_ELD_EVENTS_REQUEST = 'LOAD_ELD_EVENTS_REQUEST'
export const LOAD_ELD_EVENTS_SUCCESS = 'LOAD_ELD_EVENTS_SUCCESS'
export const LOAD_ELD_EVENTS_FAIL = 'LOAD_ELD_EVENTS_FAIL'
export const CLEAR_ELD_EVENTS = 'CLEAR_ELD_EVENTS'
// Create DRIVER LOG EVENT
export const CREATE_ADD_EVENT_REQUEST = 'CREATE_ADD_EVENT_REQUEST'
export const CREATE_ADD_EVENT_SUCCESS = 'CREATE_ADD_EVENT_SUCCESS'
export const CREATE_ADD_EVENT_FAIL = 'CREATE_ADD_EVENT_FAIL'
export const CLEAR_EVENT = 'CLEAR_EVENT'
// Master DRIVER
export const GET_DRIVER_MASTER_REQUEST = 'DRIVER_MASTER_REQUEST'
export const GET_DRIVER_MASTER_SUCCESS = 'DRIVER_MASTER_SUCCESS'
export const GET_DRIVER_MASTER_FAIL = 'DRIVER_MASTER_FAIL'
export const CLEAR_DRIVER_MASTER = 'CLEAR_DRIVER_MASTER'
// Create DRIVER LOG EVENT
export const UPDATE_EVENT_REQUEST = 'UPDATE_EVENT_REQUEST'
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS'
export const UPDATE_EVENT_FAIL = 'UPDATE_EVENT_FAIL'
// ===================== DriverHos action types Start ====================================
export const LOAD_DRIVER_HOS_REQUEST = 'LOAD_DRIVER_HOS_REQUEST'
export const LOAD_DRIVER_HOS_SUCCESS = 'LOAD_DRIVER_HOS_SUCCESS'
export const LOAD_DRIVER_HOS_FAIL = 'LOAD_DRIVER_HOS_FAIL'
export const LOAD_DRIVER_HOS_RESET = 'LOAD_DRIVER_HOS_RESET'
// transport data 
export const TRANSPORT_DATA_REQUEST = 'TRANSPORT_DATA_REQUEST'
export const TRANSPORT_DATA_SUCCESS = 'TRANSPORT_DATA_SUCCESS'
export const TRANSPORT_DATA_FAIL = 'TRANSPORT_DATA_FAIL'
export const TRANSPORT_DATA_RESET = 'TRANSPORT_DATA_RESET'
// load DRIVERHOS
export const GET_DRIVER_HOS_REQUEST = 'GET_DRIVER_HOS_REQUEST'
export const GET_DRIVER_HOS_SUCCESS = 'GET_DRIVER_HOS_SUCCESS'
export const GET_DRIVER_HOS_FAIL = 'GET_DRIVER_HOS_FAIL'
export const CLEAR_DRIVER_HOS = 'CLEAR_DRIVER_HOS'
// load Assets 
export const GET_ASSETS_REQUEST = 'GET_ASSETS_REQUEST'
export const GET_ASSETS_SUCCESS = 'GET_ASSETS_SUCCESS'
export const GET_ASSETS_FAIL = 'GET_ASSETS_FAIL'
export const CLEAR_ASSETS = 'CLEAR_ASSETS'
//load Assets Detail
export const GET_ASSETS_DETAIL_REQUEST = 'GET_ASSETS_DETAIL_REQUEST'
export const GET_ASSETS_DETAIL_SUCCESS = 'GET_ASSETS_DETAIL_SUCCESS'
export const GET_ASSETS_DETAIL_FAIL = 'GET_ASSETS_DETAIL_FAIL'
export const CLEAR_ASSETS_DETAIL = 'CLEAR_ASSETS_DETAIL'

// ifta reports 
export const GET_IFTA_RECORDS_REQUEST = 'GET_IFTA_RECORDS_REQUEST'
export const GET_IFTA_RECORDS_SUCCESS = 'GET_IFTA_RECORDS_SUCCESS'
export const GET_IFTA_RECORDS_FAIL = 'GET_IFTA_RECORDS_FAIL'
export const IFTA_RECORDS_RESET = 'IFTA_RECORDS_RESET'

//ifta reports details

export const GET_IFTA_DETAILS_REQUEST = 'GET_IFTA_DETAILS_REQUEST'
export const GET_IFTA_DETAILS_SUCCESS = 'GET_IFTA_DETAILS_SUCCESS'
export const GET_IFTA_DETAILS_FAIL = 'GET_IFTA_DETAILS_FAIL'
export const GET_IFTA_DETAILS_RESET = 'GET_IFTA_DETAILS_RESET'

//ifta reports by vehicle details

export const GET_IFTA_BY_VEHICLE_REQUEST = 'GET_IFTA_BY_VEHICLE_REQUEST'
export const GET_IFTA_BY_VEHICLE_SUCCESS = 'GET_IFTA_BY_VEHICLE_SUCCESS'
export const GET_IFTA_BY_VEHICLE_FAIL = 'GET_IFTA_BY_VEHICLE_FAIL'
export const GET_IFTA_BY_VEHICLE_RESET = 'GET_IFTA_BY_VEHICLE_RESET'

//create report vehicle

export const CREATE_REPORT_REQUEST = 'CREATE_REPORT_REQUEST'
export const CREATE_REPORT_SUCCESS = 'CREATE_REPORT_SUCCESS'
export const CREATE_REPORT_FAIL = 'CREATE_REPORT_FAIL'

// fmcsa records listing

export const GET_FMCSA_RECORDS_REQUEST = 'GET_FMCSA_RECORDS_REQUEST'
export const GET_FMCSA_RECORDS_SUCCESS = 'GET_FMCSA_RECORDS_SUCCESS'
export const GET_FMCSA_RECORDS_FAIL = 'GET_FMCSA_RECORDS_FAIL'
export const GET_FMCSA_RECORDS_RESET = 'GET_FMCSA_RECORDS_RESET'

//get all states 

export const GET_ALL_STATES_REQUEST = 'GET_ALL_STATES_REQUEST'
export const GET_ALL_STATES_SUCCESS = 'GET_ALL_STATES_SUCCESS'
export const GET_ALL_STATES_FAIL = 'GET_ALL_STATES_FAIL'
export const GET_ALL_STATES_RESET = 'GET_ALL_STATES_RESET'

// for listing alerts 
export const GET_ALERT_REQUEST = 'GET_ALERT_REQUEST'
export const GET_ALERT_SUCCESS = 'GET_ALERT_SUCCESS'
export const GET_ALERT_FAIL = 'GET_ALERT_FAIL'
export const CLEAR_GET_ALERTS = 'CLEAR_GET_ALERTS'
// Create alerts
export const CREATE_ALERT_REQUEST = 'CREATE_ALERT_REQUEST'
export const CREATE_ALERT_SUCCESS = 'CREATE_ALERT_SUCCESS'
export const CREATE_ALERT_FAIL = 'CREATE_ALERT_FAIL'
export const CLEAR_ALERT = 'CLEAR_ALERT'
//load alert 
export const LOAD_ALERT_REQUEST = 'LOAD_ALERT_REQUEST'
export const LOAD_ALERT_SUCCESS = 'LOAD_ALERT_SUCCESS'
export const LOAD_ALERT_FAIL = 'LOAD_ALERT_FAIL'
export const LOAD_ALERT_RESET = 'LOAD_ALERT_RESET'
//DELETE alert
export const DELETE_ALERT_REQUEST = 'DELETE_ALERT_REQUEST'
export const DELETE_ALERT_SUCCESS = 'DELETE_ALERT_SUCCESS'
export const DELETE_ALERT_FAIL = 'DELETE_ALERT_FAIL'
export const DELETE_ALERT_RESET = 'DELETE_ALERT_RESET'
//update alert 
export const UPDATE_ALERT_REQUEST = 'UPDATE_ALERT_REQUEST'
export const UPDATE_ALERT_SUCCESS ='UPDATE_ALERT_SUCCESS'
export const UPDATE_ALERT_FAIL = 'UPDATE_ALERT_FAIL'
export const UPDATE_ALERT_RESET = 'UPDATE_ALERT_RESET'


// ===================== admin system user action types Start ====================================

// for listing alerts 
export const GET_SYSTEM_USERS_REQUEST = 'GET_SYSTEM_USERS_REQUEST'
export const GET_SYSTEM_USERS_SUCCESS = 'GET_SYSTEM_USERS_SUCCESS'
export const GET_SYSTEM_USERS_FAIL = 'GET_SYSTEM_USERS_FAIL'
export const CLEAR_GET_SYSTEM_USERS = 'CLEAR_GET_SYSTEM_USERS'
// Create alerts
export const CREATE_SYSTEM_USER_REQUEST = 'CREATE_SYSTEM_USER_REQUEST'
export const CREATE_SYSTEM_USER_SUCCESS = 'CREATE_SYSTEM_USER_SUCCESS'
export const CREATE_SYSTEM_USER_FAIL = 'CREATE_SYSTEM_USER_FAIL'
export const CLEAR_SYSTEM_USER = 'CLEAR_SYSTEM_USER'
//load alert 
export const LOAD_SYSTEM_USER_REQUEST = 'LOAD_SYSTEM_USER_REQUEST'
export const LOAD_SYSTEM_USER_SUCCESS = 'LOAD_SYSTEM_USER_SUCCESS'
export const LOAD_SYSTEM_USER_FAIL = 'LOAD_SYSTEM_USER_FAIL'
export const LOAD_SYSTEM_USER_RESET = 'LOAD_SYSTEM_USER_RESET'
//DELETE alert
export const DELETE_SYSTEM_USER_REQUEST = 'DELETE_SYSTEM_USER_REQUEST'
export const DELETE_SYSTEM_USER_SUCCESS = 'DELETE_SYSTEM_USER_SUCCESS'
export const DELETE_SYSTEM_USER_FAIL = 'DELETE_SYSTEM_USER_FAIL'
export const DELETE_SYSTEM_USER_RESET = 'DELETE_SYSTEM_USER_RESET'
//update alert 
export const UPDATE_SYSTEM_USER_REQUEST = 'UPDATE_SYSTEM_USER_REQUEST'
export const UPDATE_SYSTEM_USER_SUCCESS ='UPDATE_SYSTEM_USER_SUCCESS'
export const UPDATE_SYSTEM_USER_FAIL = 'UPDATE_SYSTEM_USER_FAIL'
export const UPDATE_SYSTEM_USER_RESET = 'UPDATE_SYSTEM_USER_RESET'

//======================admin fmcsa logs action types start here ======================//
export const GET_FMCSA_LOGS_REQUEST = 'GET_FMCSA_LOGS_REQUEST'
export const GET_FMCSA_LOGS_SUCCESS = 'GET_FMCSA_LOGS_SUCCESS'
export const GET_FMCSA_LOGS_FAIL = 'GET_FMCSA_LOGS_FAIL'
export const CLEAR_GET_FMCSA_LOGS = 'CLEAR_GET_FMCSA_LOGS'
// create fmcsa
export const CREATE_FMCSA_LOGS_REQUEST = 'CREATE_FMCSA_LOGS_REQUEST'
export const CREATE_FMCSA_LOGS_SUCCESS = 'CREATE_FMCSA_LOGS_SUCCESS'
export const CREATE_FMCSA_LOGS_FAIL = 'CREATE_FMCSA_LOGS_FAIL'
export const CLEAR_FMCSA_LOGS = 'CLEAR_FMCSA_LOGS'
// load fmcsa
export const LOAD_FMCSA_LOGS_REQUEST = 'LOAD_FMCSA_LOGS_REQUEST'
export const LOAD_FMCSA_LOGS_SUCCESS = 'LOAD_FMCSA_LOGS_SUCCESS'
export const LOAD_FMCSA_LOGS_FAIL = 'LOAD_FMCSA_LOGS_FAIL'
export const LOAD_FMCSA_LOGS_RESET = 'LOAD_FMCSA_LOGS_RESET'
// delete fmcsa
export const DELETE_FMCSA_LOGS_REQUEST = 'DELETE_FMCSA_LOGS_REQUEST'
export const DELETE_FMCSA_LOGS_SUCCESS = 'DELETE_FMCSA_LOGS_SUCCESS'
export const DELETE_FMCSA_LOGS_FAIL = 'DELETE_FMCSA_LOGS_FAIL'
export const DELETE_FMCSA_LOGS_RESET = 'DELETE_FMCSA_LOGS_RESET'
// update fmcsa
export const UPDATE_FMCSA_LOGS_REQUEST = 'UPDATE_FMCSA_LOGS_REQUEST'
export const UPDATE_FMCSA_LOGS_SUCCESS = 'UPDATE_FMCSA_LOGS_SUCCESS'
export const UPDATE_FMCSA_LOGS_FAIL = 'UPDATE_FMCSA_LOGS_FAIL'
export const UPDATE_FMCSA_LOGS_RESET = 'UPDATE_FMCSA_LOGS_RESET'

// =====================  Start Subscription action types Start   =====================
export const LOAD_SUBSCRIPTION_REQUEST = 'LOAD_SUBSCRIPTION_REQUEST'
export const LOAD_SUBSCRIPTION_SUCCESS = 'LOAD_SUBSCRIPTION_SUCCESS'
export const LOAD_SUBSCRIPTION_FAIL = 'LOAD_SUBSCRIPTION_FAIL'
export const LOAD_SUBSCRIPTION_RESET = 'LOAD_SUBSCRIPTION_RESET'
// load SUBSCRIPTION
export const GET_BILLING_HISTORY_REQUEST = 'GET_BILLING_HISTORY_REQUEST'
export const GET_BILLING_HISTORY_SUCCESS = 'GET_BILLING_HISTORY_SUCCESS'
export const GET_BILLING_HISTORY_FAIL = 'GET_BILLING_HISTORY_FAIL'
export const CLEAR_GET_BILLING_HISTORYS = 'CLEAR_GET_BILLING_HISTORYS'
// create PAYMENT_METHOD
export const CREATE_PAYMENT_METHOD_REQUEST = 'CREATE_PAYMENT_METHOD_REQUEST'
export const CREATE_PAYMENT_METHOD_SUCCESS = 'CREATE_PAYMENT_METHOD_SUCCESS'
export const CREATE_PAYMENT_METHOD_FAIL = 'CREATE_PAYMENT_METHOD_FAIL'
// update PAYMENT_METHOD
export const UPDATE_PAYMENT_METHOD_REQUEST = 'UPDATE_PAYMENT_METHOD_REQUEST'
export const UPDATE_PAYMENT_METHOD_SUCCESS = 'UPDATE_PAYMENT_METHOD_SUCCESS'
export const UPDATE_PAYMENT_METHOD_FAIL = 'UPDATE_PAYMENT_METHOD_FAIL'
// delete PAYMENT_METHOD
export const DELETE_PAYMENT_METHOD_REQUEST = 'DELETE_PAYMENT_METHOD_REQUEST'
export const DELETE_PAYMENT_METHOD_SUCCESS = 'DELETE_PAYMENT_METHOD_SUCCESS'
export const DELETE_PAYMENT_METHOD_FAIL = 'DELETE_PAYMENT_METHOD_FAIL'
export const DELETE_PAYMENT_METHOD_RESET = 'DELETE_PAYMENT_METHOD_RESET'
// update SUBSCRIPTION
export const UPDATE_SUBSCRIPTION_REQUEST = 'UPDATE_SUBSCRIPTION_REQUEST'
export const UPDATE_SUBSCRIPTION_SUCCESS = 'UPDATE_SUBSCRIPTION_SUCCESS'
export const UPDATE_SUBSCRIPTION_FAIL = 'UPDATE_SUBSCRIPTION_FAIL'
export const UPDATE_SUBSCRIPTION_RESET = 'UPDATE_SUBSCRIPTION_RESET'
//upgrade subscription
export const UPGRADE_SUBSCRIPTION_REQUEST = 'UPGRADE_SUBSCRIPTION_REQUEST'
export const UPGRADE_SUBSCRIPTION_SUCCESS = 'UPGRADE_SUBSCRIPTION_SUCCESS'
export const UPGRADE_SUBSCRIPTION_FAIL = 'UPGRADE_SUBSCRIPTION_FAIL'
export const UPGRADE_SUBSCRIPTION_RESET = 'UPGRADE_SUBSCRIPTION_RESET'
//get SUBSCRIPTION
export const GET_SUBSCRIPTION_REQUEST = 'GET_SUBSCRIPTION_REQUEST'
export const GET_SUBSCRIPTION_SUCCESS = 'GET_SUBSCRIPTION_SUCCESS'
export const GET_SUBSCRIPTION_FAIL = 'GET_SUBSCRIPTION_FAIL'
export const GET_SUBSCRIPTION_RESET = 'GET_SUBSCRIPTION_RESET'
//cancel SUBSCRIPTION
export const CANCEL_SUBSCRIPTION_REQUEST = 'CANCEL_SUBSCRIPTION_REQUEST'
export const CANCEL_SUBSCRIPTION_SUCCESS = 'CANCEL_SUBSCRIPTION_SUCCESS'
export const CANCEL_SUBSCRIPTION_FAIL = 'CANCEL_SUBSCRIPTION_FAIL'
export const CANCEL_SUBSCRIPTION_RESET = 'CANCEL_SUBSCRIPTION_RESET'
// get payment method 
export const GET_PAYMENT_METHOD_REQUEST = 'GET_PAYMENT_METHOD_REQUEST'
export const GET_PAYMENT_METHOD_SUCCESS = 'GET_PAYMENT_METHOD_SUCCESS'
export const GET_PAYMENT_METHOD_FAIL = 'GET_PAYMENT_METHOD_FAIL'
export const CLEAR_PAYMENT_METHOD_RESET = 'CLEAR_PAYMENT_METHOD_RESET'
//get upgraded plan method
export const GET_UPGRADED_PLAN_REQUEST = 'GET_UPGRADED_PLAN_REQUEST'
export const GET_UPGRADED_PLAN_SUCCESS = 'GET_UPGRADED_PLAN_SUCCESS'
export const GET_UPGRADED_PLAN_FAIL = 'GET_UPGRADED_PLAN_FAIL'
export const CLEAR_GET_UPGRADED_PLAN = 'CLEAR_GET_UPGRADED_PLAN'
//get default payment method 
export const CREATE_DEFAULT_PAYMENT_REQUEST = 'CREATE_DEFAULT_PAYMENT_REQUEST'
export const CREATE_DEFAULT_PAYMENT_SUCCESS = 'CREATE_DEFAULT_PAYMENT_SUCCESS'
export const CREATE_DEFAULT_PAYMENT_FAIL = 'CREATE_DEAFULT_PAYMENT_FAIL'
export const CREATE_DEFAULT_PAYMENT_CLEAR = 'CREATE_DEFAULT_PAYMENT_CLEAR'
// =====================  End Subscription action types Start   =====================
//get resources 
export const GET_RESOURCE_REQUEST = 'GET_RESOURCE_REQUEST'
export const GET_RESOURCE_SUCCESS = 'GET_RESOURCE_SUCCESS'
export const GET_RESOURCE_FAIL = 'GET_RESOURCE_FAIL'
export const CLEAR_GET_RESOURCE = 'CLEAR_GET_RESOURCE'

//LOCATION SHARING
export const GET_CREATELOCATION_REQUEST = 'GET_CREATELOCATION_REQUEST'
export const GET_CREATELOCATION_SUCCESS = 'GET_CREATELOCATION_SUCCESS'
export const GET_CREATELOCATION_FAIL = 'GET_CREATELOCATION_FAIL'
export const CLEAR_GET_CREATELOCATION = 'CLEAR_GET_CREATELOCATION'

//DEACTIVATE LOCATION SHARING
export const GET_DEACTIVATE_REQUEST = 'GET_DEACTIVATE_REQUEST'
export const GET_DEACTIVATE_SUCCESS = 'GET_DEACTIVATE_SUCCESS'
export const GET_DEACTIVATE_FAIL = 'GET_DEACTIVATE_FAIL'
export const CLEAR_GET_DEACTIVATE = 'CLEAR_GET_DEACTIVATE'

// LOCATION DATA SHARING
export const GET_LOCATIONDATA_REQUEST = 'GET_LOCATIONDATA_REQUEST'
export const GET_LOCATIONDATA_SUCCESS = 'GET_LOCATIONDATA_SUCCESS'
export const GET_LOCATIONDATA_FAIL = 'GET_LOCATIONDATA_FAIL'
export const CLEAR_GET_LOCATIONDATA = 'CLEAR_GET_LOCATIONDATA'

