// =====================      Dashboard action types START    =========================

export const GET_PROJECT_REQUEST = 'GET_PROJECT_REQUEST'
export const GET_PROJECT_SUCCESS = 'GET_PROJECT_SUCCESS'
export const GET_PROJECT_FAIL = 'GET_PROJECT_FAIL'
export const CLEAR_GET_PROJECTS = 'CLEAR_GET_PROJECTS'
// PROJECT MEMBERS
export const GET_PROJECT_MEMBER_REQUEST = 'GET_PROJECT_MEMBER_REQUEST'
export const GET_PROJECT_MEMBER_SUCCESS = 'GET_PROJECT_MEMBER_SUCCESS'
export const GET_PROJECT_MEMBER_FAIL = 'GET_PROJECT_MEMBER_FAIL'
// PROJECT OBJECTIVE
export const PROJECT_OBJECTIVE_TYPES_REQUEST = 'PROJECT_OBJECTIVE_TYPES_REQUEST'
export const PROJECT_OBJECTIVE_TYPES_SUCCESS = 'PROJECT_OBJECTIVE_TYPES_SUCCESS'
export const PROJECT_OBJECTIVE_TYPES_FAIL = 'PROJECT_OBJECTIVE_TYPES_FAIL'

// ========================= dashboard count ================================

export const GET_DASHBOARD_COUNT_REQUEST = 'GET_DASHBOARD_COUNT_REQUEST'
export const GET_DASHBOARD_COUNT_SUCCESS = 'GET_DASHBOARD_COUNT_SUCCESS'
export const GET_DASHBOARD_COUNT_FAIL = 'GET_DASHBOARD_COUNT_FAIL'
export const GET_DASHBOARD_COUNT_RESET = 'GET_DASHBOARD_COUNT_RESET'

//===========================dashboard vehicle and driver data =========================

export const GET_VEHICLE_AND_DRIVER_REQUEST = 'GET_VEHICLE_AND_DRIVER_REQUEST'
export const GET_VEHICLE_AND_DRIVER_SUCCESS = 'GET_VEHICLE_AND_DRIVER_SUCCESS'
export const GET_VEHICLE_AND_DRIVER_FAIL = 'GET_VEHICLE_AND_DRIVER_FAIL'
export const GET_VEHICLE_AND_DRIVER_RESET = 'GET_VEHICLE_AND_DRIVER_RESET'

export const SET_MINIMIZE_REQUEST = 'SET_MINIMIZE_REQUEST'
export const SET_OPEN_MOBILE_REQUEST = 'SET_OPEN_MOBILE_REQUEST';
export const SET_COLOR_THEME_REQUEST = 'SET_COLOR_THEME_REQUEST';
